### ISSUE TITLE
[not really an issue] Steps to replicate Intellij Nord theme

### ISSUE THREAD

**Issue by turutupa** [nordtheme/jetbrains#196]
Hi! I love the pictures of your Nord theme with the minimalistic aesthetics. Could you provide the steps or some info on how to remove some of the clutter intellij has by default? 

I like how you moved the action buttons to the left on top of the project file explorer and how the project file explorer is actually on top of the bottom bar.

**Comment by svengreb** [comment]
Hi @turutupa :wave:, nice to see that you like it 😊

The [menus and toolbars can be configured through the IDE preferences][1].
Basically I've removed all toolbars and icons from the “Main Toolbar“ section except for “Toolbar Run Actions“ and also removed some unused items from it. By default there are way too much (useless) elements in the toolbar like e.g. the “YouTrack“ integration etc. and I like to keep my setup minimal.

My configurations are [also stored in my _.dotfile_ repository][2]. Note that they are currently out-of-date and I need to push my current configurations for the latest IDE versions, but maybe it helps you to underdtand how to persist such configuration across systems and major IDE updates.

[1]: https://www.jetbrains.com/help/idea/customize-actions-menus-and-toolbars.html#show-hide
[2]: https://github.com/arcticicestudio/igloo/tree/38e9cd4e/snowblocks/jetbrains

**Comment by turutupa** [comment]
Thank you so much! I've only been using Intellij for around a year and didn't know it could be customized so much. I've cleaned it up a little now (thanks for the dotfiles!) and it looks so nice and clear of unnecessary clutter 👏👏👏👏🙌🙌🙌🙌

Thank you @svengreb! 
Closing "issue".

**Comment by turutupa** [comment]
Oh, and before closing. 

There is only one menu I end up needing more than I would like to. The main menu, or main toolbar. You can quickly enable and disable it using the ctrl + shift + n and in actions enable/disable; but was wondering if there is a faster way? Cause normally I have it disabled most of the time, but its kind of annoying having to enable it just to click somewhere, and then disable again. 

Maybe I should get used to using ctrl + shift + n and search directly for what I want. Not sure about this.

**Comment by KTibow** [comment]
Do you want to actually close this issue?
