### ISSUE TITLE
Unthemed custom HTML tags

### ISSUE THREAD

**Issue by AustinMcCallister** [nordtheme/jetbrains#206]
I'm not sure if this is a new update specific to angular, or for HTML in general, but there is a new HTML color called "custom tag name" which is currently using the default color from the dark theme

![image](https://user-images.githubusercontent.com/93660712/206061016-a8754632-da5a-4fb5-ab1b-3b087ab27a79.png)

It is located in the color scheme settings under HTML, I wasn't sure what color in the nord palette would best fit this item, but prior to 2022.3 I think it just used the same blue color as regular HTML tags

![image](https://user-images.githubusercontent.com/93660712/206061243-1134cd9b-f951-462d-bdf4-c5567892304e.png)

**Comment by KTibow** [comment]
- In the default theme, custom tags are the same color as regular tags
- It looks like this was fixed, now custom tags are the same color as regular tags, can you close this issue?
![image](https://github.com/nordtheme/jetbrains/assets/10727862/b20bbe5f-3b80-459f-afa5-de186a824a1e)

**Comment by AustinMcCallister** [comment]
Sure thing, looks normal.
